# Generated by Django 2.2.20 on 2022-01-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0008_auto_20220112_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(editable=False, max_length=30, verbose_name='IP 地址')),
                ('location', models.CharField(editable=False, max_length=30, verbose_name='IP 地理位置')),
                ('os_info', models.CharField(editable=False, max_length=16, verbose_name='系统')),
                ('browser', models.CharField(editable=False, max_length=128, verbose_name='浏览器')),
                ('liked_articles', models.ManyToManyField(related_query_name='articles_liked', to='blog.Article', verbose_name='点赞的文章')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
            },
        ),
    ]
