# Generated by Django 2.2.20 on 2022-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_ouser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='nickname',
            field=models.CharField(default='无名氏', max_length=64, unique=True, verbose_name='昵称'),
        ),
    ]
